name: Build Python CLI Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .exe
        run: |
          pyinstaller --onefile --name "MyGame" my_game.py
        # The executable will be in the `dist` folder

      - name: Upload .exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyGame-Windows
          path: dist/MyGame.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .app
        run: |
          pyinstaller --onefile --name "MyGame" --windowed my_game.py
        # The `.app` file will be in the `dist` folder

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyGame-macOS
          path: dist/MyGame.app
